version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: api
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
